version: '3.8'

services:

  backend:
    build: ./backend
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://user:pwd@db:5432/db
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 4200:4200
  db:
    image: postgres:15.1
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
      - POSTGRES_DB=db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
  